import { useState } from 'react';
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, BookOpen, CheckCircle2, Info, Menu, Plane, X } from 'lucide-react';

const api={
  composite:107.76,
  horizons:[['T+1',112.90,7596.8],['T+7',114.64,7569.38],['T+15',103.50,7124.38],['T+21',100,6821.47]],
  routes:[
    ['DEL-BOM','Delhi ↔ Mumbai',44.7562,64524534,6635,101.61],
    ['DEL-BLR','Delhi ↔ Bengaluru',29.8853,43085268,9771,110.67],
    ['BLR-BOM','Bengaluru ↔ Mumbai',25.3586,36559204,6732,135.45]
  ],
  airlines:[['IndiGo',7780],['Air India',7650],['Akasa Air',7550],['Air India Express',8000],['SpiceJet',8050]]
};
const money=n=>`₹${Math.round(n).toLocaleString('en-IN')}`;
function Help({children}){return <span className="help-icon"><Info size={13}/><span>{children}</span></span>}
function Section({id,kicker,title,children}){return <section id={id} className="section"><div className="section-title"><span>{kicker}</span><h2>{title}</h2></div>{children}</section>}
export default function FriendlyDashboard(){
 const [open,setOpen]=useState(false); const [selected,setSelected]=useState('T+1'); const [showFormula,setShowFormula]=useState(false);
 const current=api.horizons.find(x=>x[0]===selected);
 const nav=[['overview','Overview'],['index','Airfare Index'],['routes','Routes'],['learn','How it works'],['quality','Data quality'],['method','Methodology']];
 const go=id=>{setOpen(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})};
 return <div className="friendly-app">
  <aside className={open?'friendly-side open':'friendly-side'}><div className="friendly-brand"><div className="plane-logo"><Plane size={19}/></div><div><b>Airfare Index</b><small>APIx · India</small></div><button className="close-side" onClick={()=>setOpen(false)}><X/></button></div><div className="nav-caption">MENU</div>{nav.map(([id,label])=><button className="friendly-nav" key={id} onClick={()=>go(id)}>{id==='routes'?<Plane size={16}/>:id==='quality'?<CheckCircle2 size={16}/>:id==='learn'||id==='method'?<BookOpen size={16}/>:<Activity size={16}/>} {label}</button>)}<div className="pilot-box"><b>PILOT DATA</b><p>Collected airfare observations used to demonstrate how APIx works. Not live ticket prices.</p></div></aside>
  <main className="friendly-main"><header className="friendly-top"><button className="menu-btn" onClick={()=>setOpen(true)}><Menu/></button><span>India domestic aviation</span><b>4 September 2026</b></header>
   <section id="overview" className="friendly-hero"><div><span className="eyebrow">In simple words</span><h1>Are flight prices going up or down?</h1><p>APIx — the Airfare Price Index — combines many domestic airfare observations into one number that is easy to compare.</p></div><div className="hero-score"><small>Current pilot APIx</small><strong>{api.composite.toFixed(2)}</strong><span>100 = base level</span></div></section>
   <div className="important"><Info size={18}/><div><b>One important point</b><p><strong>107.76 is an index level, not 7.76% inflation.</strong> We currently have one collection period. We need repeated collections over time before we can calculate real airfare inflation.</p></div></div>

   <Section id="index" kicker="01 · THE MAIN NUMBER" title="Airfare Price Index"><div className="two-col"><div className="simple-card index-card"><div className="label">Pilot APIx</div><div className="huge">{api.composite.toFixed(2)}</div><h3>What does 107.76 mean?</h3><p>Imagine the starting price level is set to <b>100</b>. This pilot's combined airfare level is <b>7.76 index points higher</b> than that starting level.</p><div className="base-scale"><span>Lower</span><b>100 = starting point</b><span>Higher</span></div><div className="scale-track"><i/><i/><i/></div></div><div className="simple-card"><div className="card-heading">Booking horizon <Help>T+ means “days before the flight”. T+1 is one day before travel; T+21 is 21 days before travel.</Help></div><p className="plain">The same flight can cost different amounts depending on when you book. Select a horizon:</p><div className="horizon-grid">{api.horizons.map(x=><button key={x[0]} className={selected===x[0]?'selected':''} onClick={()=>setSelected(x[0])}><b>{x[0]}</b><strong>{x[1].toFixed(2)}</strong><small>{money(x[2])}</small></button>)}</div><div className="selection"><span>Selected</span><b>{selected}</b><strong>{current[1].toFixed(2)}</strong><small>Typical observed fare: {money(current[2])}</small></div></div></div>
    <div className="simple-card chart-card"><div className="card-heading">Index by booking horizon <Help>The taller the bar, the higher that horizon's fare level is compared with the base of 100.</Help></div><ResponsiveContainer width="100%" height={280}><BarChart data={api.horizons.map(x=>({horizon:x[0],index:x[1]}))}><CartesianGrid vertical={false} stroke="#dfe5ea"/><XAxis dataKey="horizon" tick={{fontSize:12}} axisLine={false} tickLine={false}/><YAxis domain={[90,120]} tick={{fontSize:11}} axisLine={false} tickLine={false}/><Tooltip formatter={v=>[Number(v).toFixed(2),'Index']} contentStyle={{borderRadius:10,border:'1px solid #dfe5ea'}}/><Bar dataKey="index" radius={[8,8,0,0]}>{api.horizons.map((_,i)=><Cell key={i}/>)}</Bar></BarChart></ResponsiveContainer><div className="explain"><b>In plain English:</b> T+1 and T+7 are above the 100 starting point in this pilot. T+21 is the reference level.</div></div></Section>

   <Section id="routes" kicker="02 · WHERE PEOPLE FLY" title="Routes that influence the index"><p className="section-intro">Busier routes get more weight. That means a route used by more passengers has a bigger effect on the combined APIx.</p><div className="route-grid">{api.routes.map(r=><div className="simple-card route-card" key={r[0]}><div className="route-line"><b>{r[0]}</b><span>{r[2].toFixed(2)}%</span></div><h3>{r[1]}</h3><div className="route-price">{money(r[4])}<small>median fare at T+1</small></div><div className="route-details"><span><b>{r[5].toFixed(2)}</b> route index</span><span>{(r[3]/1e6).toFixed(1)}M passengers</span></div><div className="weight"><i style={{width:`${r[2]}%`}}/></div><small className="muted">Route weight = passenger share in this pilot.</small></div>)}</div><div className="simple-card note"><b>Why weights?</b><p>If Delhi–Mumbai has about 45% of the passenger weight, a change on that route matters more to the combined index than a change on a route with 25% weight.</p></div></Section>

   <Section id="learn" kicker="03 · NO TECHNICAL KNOWLEDGE NEEDED" title="How to understand the dashboard"><div className="learn-grid">{[['Index','A summary number. 100 is the chosen starting point. 110 means the measured price level is 10 index points above it.'],['Base','The starting period used for comparison. We set its index value to 100.'],['T+1, T+7…','How many days before travel the fare was observed.'],['Median fare','The middle value after sorting fares from low to high. It reduces the effect of unusually cheap or expensive tickets.'],['Route weight','The percentage influence a route has on the combined index, based here on passenger traffic.'],['Observation','One recorded fare for a specific flight, airline, date and booking horizon.']].map(x=><div className="learn-item" key={x[0]}><div className="learn-icon">?</div><div><b>{x[0]}</b><p>{x[1]}</p></div></div>)}</div></Section>

   <Section id="quality" kicker="04 · TRUST THE DATA" title="Data quality & coverage"><div className="quality-grid">{[['161','raw fare records'],['124','qualifying observations'],['3','pilot routes'],['12/12','route × horizon cells complete']].map(x=><div className="simple-card quality" key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div><div className="simple-card quality-message"><CheckCircle2/><div><b>What was checked?</b><p>Non-stop economy observations were retained; horizon labels were standardized; duplicate/source records were reconciled; and the final dataset has observations for every route × horizon combination used in the pilot.</p></div></div></Section>

   <Section id="method" kicker="05 · BEHIND THE NUMBER" title="Methodology, without the jargon"><div className="steps">{[['1','Collect fares','Record comparable one-way economy fares.'],['2','Find the median','Find the middle fare for each route and booking horizon.'],['3','Compare','Compare each current fare level with its base level.'],['4','Weight & combine','Give busier routes more influence and combine the four horizons.']].map(x=><div className="step" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><p>{x[2]}</p></div>)}</div><button className="formula-btn" onClick={()=>setShowFormula(!showFormula)}>{showFormula?'Hide':'Show'} technical formula</button>{showFormula&&<pre>APIx = Σ (route weight × horizon weight × current price ÷ base price × 100){`\n`}Pilot horizon weights: 25% each for T+1, T+7, T+15 and T+21.</pre>}<div className="next-box"><b>What happens next?</b><p>Collect the same observations again in future periods. Once we have multiple periods, the project can calculate genuine airfare changes over time instead of only a pilot level.</p></div></Section>

   <footer>APIx · Airfare Price Index · Pilot data dated 4 September 2026 · Transparent, explainable and designed for everyone.</footer>
  </main>
 </div>
}
